"""
Example: Using Generated ROI CSVs with MEDiml

This script demonstrates how to use the CSV files generated by generate_roi_csv.py
in your MEDiml feature extraction pipeline.
"""

import pandas as pd
from pathlib import Path


def example_1_load_generated_csv():
    """Example 1: Load a generated CSV file and inspect its structure."""
    print("="*80)
    print("EXAMPLE 1: Loading Generated ROI CSV")
    print("="*80)
    
    # Path to generated CSV (update with your actual path)
    csv_path = Path(__file__).parent.parent / 'dataset' / 'roi_csv' / 'roiNames_Tumor.csv'
    
    if not csv_path.exists():
        print(f"⚠️  File not found: {csv_path}")
        print("Please generate ROI CSVs first using:")
        print("  python generate_roi_csv.py --dataset-path /path/to/dataset")
        return
    
    # Load CSV
    df = pd.read_csv(csv_path)
    
    print(f"\nLoaded: {csv_path}")
    print(f"Shape: {df.shape[0]} rows, {df.shape[1]} columns")
    print(f"\nColumns: {list(df.columns)}")
    print(f"\nFirst 5 rows:")
    print(df.head().to_string(index=False))
    print(f"\nUnique patients: {df['PatientID'].nunique()}")
    print(f"Unique scans: {df['ImagingScanName'].nunique()}")


def example_2_compare_options():
    """Example 2: Compare different ROI options for the same dataset."""
    print("\n" + "="*80)
    print("EXAMPLE 2: Comparing Different ROI Options")
    print("="*80)
    
    roi_csv_dir = Path(__file__).parent.parent / 'dataset' / 'roi_csv'
    
    # Find all generated CSV files
    csv_files = sorted(roi_csv_dir.glob('roiNames_*.csv'))
    
    if not csv_files:
        print(f"⚠️  No CSV files found in {roi_csv_dir}")
        return
    
    print(f"\nFound {len(csv_files)} ROI CSV files:")
    
    data_dict = {}
    for csv_file in csv_files:
        df = pd.read_csv(csv_file)
        data_dict[csv_file.stem] = df
        print(f"\n  📄 {csv_file.name}")
        print(f"     Rows: {len(df)}")
        print(f"     Unique ROI combinations: {df['ROIname'].nunique()}")
        print(f"     Sample ROIs: {df['ROIname'].unique()[:3].tolist()}")
    
    # Compare Option A vs Option C
    option_a_files = [f for f in data_dict.keys() if 'combined' not in f and 'subtract' not in f]
    option_c_files = [f for f in data_dict.keys() if 'combined' in f]
    
    if option_a_files and option_c_files:
        print("\n" + "-"*80)
        print("COMPARISON: Option A (Single ROI) vs Option C (Combined ROIs)")
        print("-"*80)
        
        df_a = data_dict[option_a_files[0]]
        df_c = data_dict[option_c_files[0]]
        
        print(f"\nOption A - Single ROI per patient:")
        print(f"  Unique ROI specifications: {df_a['ROIname'].nunique()}")
        print(f"  Example: {df_a['ROIname'].iloc[0]}")
        
        print(f"\nOption C - Combined ROIs:")
        print(f"  Unique ROI specifications: {df_c['ROIname'].nunique()}")
        print(f"  Example: {df_c['ROIname'].iloc[0]}")


def example_3_update_imaging_modality():
    """Example 3: Update ImagingModality based on ImagingScanName."""
    print("\n" + "="*80)
    print("EXAMPLE 3: Updating ImagingModality Column")
    print("="*80)
    
    csv_path = Path(__file__).parent.parent / 'dataset' / 'roi_csv' / 'roiNames_Tumor.csv'
    
    if not csv_path.exists():
        print(f"⚠️  File not found: {csv_path}")
        return
    
    df = pd.read_csv(csv_path)
    
    print(f"\nOriginal ImagingModality values:")
    print(df['ImagingModality'].unique())
    
    # Define mapping from ImagingScanName to ImagingModality
    modality_map = {
        'CT': 'CTscan',
        'PT': 'PTscan',
        'PET': 'PTscan',
        'MR_T1': 'MRscan',
        'MR_T2': 'MRscan',
        'T1': 'MRscan',
        'T2': 'MRscan',
        'Dose': 'MRscan'  # Or CTscan depending on your acquisition
    }
    
    # Apply mapping
    df['ImagingModality'] = df['ImagingScanName'].map(modality_map)
    
    print(f"\nUpdated ImagingModality values:")
    print(df['ImagingModality'].unique())
    
    # Save updated CSV
    output_path = csv_path.parent / f'{csv_path.stem}_updated.csv'
    df.to_csv(output_path, index=False)
    print(f"\n✅ Saved updated CSV to: {output_path}")
    print(f"\nPreview:")
    print(df[['PatientID', 'ImagingScanName', 'ImagingModality', 'ROIname']].head().to_string(index=False))


def example_4_filter_by_modality():
    """Example 4: Filter CSV to specific imaging modality."""
    print("\n" + "="*80)
    print("EXAMPLE 4: Filtering CSV by Imaging Modality")
    print("="*80)
    
    csv_path = Path(__file__).parent.parent / 'dataset' / 'roi_csv' / 'roiNames_Tumor.csv'
    
    if not csv_path.exists():
        print(f"⚠️  File not found: {csv_path}")
        return
    
    df = pd.read_csv(csv_path)
    
    print(f"\nOriginal dataset: {len(df)} rows")
    print(f"Available modalities: {df['ImagingModality'].unique().tolist()}")
    
    # Filter to CT only
    df_ct_only = df[df['ImagingModality'] == 'CTscan'].copy()
    
    print(f"\nFiltered to CTscan only: {len(df_ct_only)} rows")
    print(f"Unique patients: {df_ct_only['PatientID'].nunique()}")
    
    # Save filtered version
    output_path = csv_path.parent / f'{csv_path.stem}_CTonly.csv'
    df_ct_only.to_csv(output_path, index=False)
    print(f"\n✅ Saved filtered CSV to: {output_path}")


def example_5_analyze_roi_statistics():
    """Example 5: Analyze statistics of generated ROIs."""
    print("\n" + "="*80)
    print("EXAMPLE 5: ROI Statistics Analysis")
    print("="*80)
    
    csv_path = Path(__file__).parent.parent / 'dataset' / 'roi_csv' / 'roiNames_Tumor.csv'
    
    if not csv_path.exists():
        print(f"⚠️  File not found: {csv_path}")
        return
    
    df = pd.read_csv(csv_path)
    
    print(f"\n📊 Dataset Statistics:")
    print(f"  Total rows: {len(df)}")
    print(f"  Total patients: {df['PatientID'].nunique()}")
    print(f"  Total scans: {df['ImagingScanName'].nunique()}")
    print(f"  Unique ROI combinations: {df['ROIname'].nunique()}")
    
    print(f"\n📊 Imaging Modality Breakdown:")
    modality_counts = df['ImagingModality'].value_counts()
    for modality, count in modality_counts.items():
        percentage = (count / len(df)) * 100
        print(f"  {modality}: {count} ({percentage:.1f}%)")
    
    print(f"\n📊 Top 5 ROI Combinations:")
    roi_counts = df['ROIname'].value_counts()
    for roi, count in roi_counts.head(5).items():
        print(f"  {roi}: {count} patients")
    
    print(f"\n📊 Scans per Patient:")
    scans_per_patient = df.groupby('PatientID').size()
    print(f"  Average: {scans_per_patient.mean():.1f}")
    print(f"  Min: {scans_per_patient.min()}")
    print(f"  Max: {scans_per_patient.max()}")


def example_6_create_analysis_variants():
    """Example 6: Create multiple analysis variants from different ROI options."""
    print("\n" + "="*80)
    print("EXAMPLE 6: Creating Analysis Variants")
    print("="*80)
    
    roi_csv_dir = Path(__file__).parent.parent / 'dataset' / 'roi_csv'
    
    # Example: Create three different analysis variants
    variants = {
        'analysis_single_roi': 'roiNames_Tumor.csv',
        'analysis_combined_roi': 'roiNames_Tumor_combined.csv',
        'analysis_edge': 'roiNames_Tumor_subtract*.csv'  # Pattern for subtractions
    }
    
    print(f"\nDefining analysis variants:")
    
    for variant_name, csv_pattern in variants.items():
        matching_files = list(roi_csv_dir.glob(csv_pattern))
        if matching_files:
            csv_file = matching_files[0]
            df = pd.read_csv(csv_file)
            print(f"\n  ✅ {variant_name}")
            print(f"     File: {csv_file.name}")
            print(f"     Patients: {df['PatientID'].nunique()}")
            print(f"     Sample ROI: {df['ROIname'].iloc[0]}")


if __name__ == '__main__':
    print("\n" + "="*80)
    print("MEDiml - ROI CSV Usage Examples")
    print("="*80)
    
    # Run all examples
    example_1_load_generated_csv()
    example_2_compare_options()
    example_3_update_imaging_modality()
    example_4_filter_by_modality()
    example_5_analyze_roi_statistics()
    example_6_create_analysis_variants()
    
    print("\n" + "="*80)
    print("Examples completed!")
    print("="*80)
    print("\n📖 For more information, see: GENERATE_ROI_CSV_GUIDE.md")
